/**
 * @type {import('~/theme/ThemeTokenContract.js').TitanTheme}
 * The built-in Heritage Dark theme: TITAN's pastel identity colors on a deep blue-grey neutral ramp.
 * Every colored fill pairs with a deep matching text color so no surface renders light text on a
 * saturated fill.
 */
const HERITAGE_DARK = Object.freeze({
   id: 'heritage-dark',
   name: 'Heritage Dark',
   dark: true,
   tokens: Object.freeze({
      'app-background': '#262836',
      'app-font-color': '#d8dbe8',
      'border-color': '#4d5063',
      'window-content-background': '#262836',
      'content-link-font-color': '#191813',
      'editor-menu-color': '#191813',
      'scrollbar-color': '#f2b58c',
      'scrollbar-gutter-color': '#1b1c26',
      'highlighted-background': '#ffe9ae',
      'highlighted-font-color': '#3d3304',
      'panel-1-background': '#373949',
      'panel-1-color': '#d8dbe8',
      'panel-2-background': '#424557',
      'panel-2-color': '#d8dbe8',
      'panel-3-background': '#2e303c',
      'panel-3-color': '#d8dbe8',
      'button-background': '#f2b58c',
      'button-font-color': '#3d2a18',
      'button-border-color': '#1b1c26',
      'button-hover-background': '#f8d2bb',
      'button-hover-border-color': '#3d2a18',
      'button-hover-font-color': '#3d2a18',
      'button-disabled-background': '#6b6e80',
      'button-disabled-border-color': '#4d5063',
      'button-disabled-font-color': '#262836',
      'input-background': '#c5bcf8',
      'input-font-color': '#23184d',
      'input-border-color': '#1b1c26',
      'input-hover-background': '#ddd6fb',
      'input-hover-border-color': '#23184d',
      'input-hover-font-color': '#23184d',
      'input-disabled-background': '#6b6e80',
      'input-disabled-border-color': '#4d5063',
      'input-disabled-font-color': '#262836',
      'label-background': '#a6ccf2',
      'label-font-color': '#152a3d',
      'label-border-color': '#1b1c26',
      'tag-background': '#a6ccf2',
      'tag-font-color': '#152a3d',
      'tag-border-color': '#1b1c26',
      'calculated-value-background': '#1f2130',
      'calculated-value-font-color': '#9da3ba',
      'calculated-value-border-color': '#4d5063',
      'body-background': '#f29d8c',
      'body-font-color': '#3d1f18',
      'mind-background': '#95f28c',
      'mind-font-color': '#1c3d18',
      'soul-background': '#b5f2e8',
      'soul-font-color': '#143d36',
      'reflexes-background': '#eff49a',
      'reflexes-font-color': '#3a3d14',
      'resilience-background': '#f2c88c',
      'resilience-font-color': '#3d2a14',
      'willpower-background': '#f28cbf',
      'willpower-font-color': '#3d1429',
      'stamina-background': '#37da88',
      'stamina-font-color': '#0c2e1c',
      'resolve-background': '#3fb6dd',
      'resolve-font-color': '#0a2730',
      'wounds-background': '#c55858',
      'wounds-font-color': '#f7e3e3',
      'uncommon-background': '#d0ffbb',
      'uncommon-font-color': '#1f3d14',
      'rare-background': '#ffdeac',
      'rare-font-color': '#3d2e14',
      'unique-background': '#ffcfee',
      'unique-font-color': '#3d1430',
      'critical-success-background': '#87cefa',
      'critical-success-font-color': '#0d2b45',
      'success-background': '#90ee90',
      'success-font-color': '#14391c',
      'failure-background': '#ffd700',
      'failure-font-color': '#3d3304',
      'critical-failure-background': '#ffa07a',
      'critical-failure-font-color': '#401d0d',
      'succeeded-font-color': '#8fd0ff',
      'failed-font-color': '#ff9d9d',
      'lesser-background': '#ffd1d1',
      'lesser-color': '#8b0000',
      'greater-background': '#c5ffeb',
      'greater-color': '#023020',
      'meter-background': '#1b1c26',
      'custom-effect-primary': '#9580ff',
      'custom-effect-secondary': '#ffff80',
      'custom-effect-font-color': '#1b1c26',
      'expired-effect-primary': '#ffff80',
      'expired-effect-secondary': '#ff9580',
      'expired-effect-font-color': '#1b1c26',
      'initiative-effect-primary': '#ff9580',
      'initiative-effect-secondary': '#9580ff',
      'initiative-effect-font-color': '#1b1c26',
      'permanent-effect-primary': '#80ffea',
      'permanent-effect-secondary': '#8aff80',
      'permanent-effect-font-color': '#1b1c26',
      'turn-end-effect-primary': '#ff80bf',
      'turn-end-effect-secondary': '#9580ff',
      'turn-end-effect-font-color': '#1b1c26',
      'turn-start-effect-primary': '#9580ff',
      'turn-start-effect-secondary': '#80ffea',
      'turn-start-effect-font-color': '#1b1c26',
      'chat-public-background': '#2e3044',
      'chat-public-header-background': '#262836',
      'chat-public-badge-background': '#424557',
      'chat-public-badge-font-color': '#d8dbe8',
      'chat-secret-background': '#2c2a4e',
      'chat-secret-header-background': '#232148',
      'chat-secret-badge-background': '#3b3878',
      'chat-secret-badge-font-color': '#cecdf8',
      'chat-gm-background': '#3a2440',
      'chat-gm-header-background': '#2f1c35',
      'chat-gm-badge-background': '#5c3866',
      'chat-gm-badge-font-color': '#eed3f5',
      'font-family-normal': "'Lato'",
      'font-family-rich-text': "'Open Sans'",
   }),
});

export default HERITAGE_DARK;
