/**
 * @type {import('~/theme/ThemeTokenContract.js').TitanTheme}
 * The built-in Catppuccin Macchiato theme: TITAN's identity hues mapped onto the official Catppuccin
 * Macchiato accents over its warm-dark base ramp. Palette values from catppuccin/palette
 * (MIT © Catppuccin Org — https://github.com/catppuccin/palette).
 */
const MACCHIATO = Object.freeze({
   id: 'macchiato',
   name: 'Catppuccin Macchiato',
   dark: true,
   tokens: Object.freeze({
      'app-background': '#24273a',
      'app-font-color': '#cad3f5',
      'border-color': '#5b6078',
      'window-content-background': '#24273a',
      'content-link-font-color': '#191813',
      'editor-menu-color': '#191813',
      'scrollbar-color': '#f5a97f',
      'scrollbar-gutter-color': '#181926',
      'highlighted-background': '#eed49f',
      'highlighted-font-color': '#3d2e0a',
      'heading-font-color': '#cad3f5',
      'accent-color': '#91d7e3',
      'panel-1-background': '#363a4f',
      'panel-1-color': '#cad3f5',
      'panel-2-background': '#494d64',
      'panel-2-color': '#cad3f5',
      'panel-3-background': '#1e2030',
      'panel-3-color': '#cad3f5',
      'button-background': '#f5a97f',
      'button-font-color': '#3a2412',
      'button-border-color': '#181926',
      'button-hover-background': '#f8c4a0',
      'button-hover-border-color': '#3a2412',
      'button-hover-font-color': '#3a2412',
      'button-disabled-background': '#5b6078',
      'button-disabled-border-color': '#494d64',
      'button-disabled-font-color': '#24273a',
      'input-background': '#b7bdf8',
      'input-font-color': '#1e2030',
      'input-border-color': '#181926',
      'input-hover-background': '#cdd1fa',
      'input-hover-border-color': '#1e2030',
      'input-hover-font-color': '#1e2030',
      'input-disabled-background': '#5b6078',
      'input-disabled-border-color': '#494d64',
      'input-disabled-font-color': '#24273a',
      'label-background': '#8aadf4',
      'label-font-color': '#11244d',
      'label-border-color': '#181926',
      'tag-background': '#8aadf4',
      'tag-font-color': '#11244d',
      'tag-border-color': '#181926',
      'calculated-value-background': '#1e2030',
      'calculated-value-font-color': '#a5adcb',
      'calculated-value-border-color': '#5b6078',
      'body-background': '#ed8796',
      'body-font-color': '#401219',
      'mind-background': '#a6da95',
      'mind-font-color': '#15330e',
      'soul-background': '#8bd5ca',
      'soul-font-color': '#0e332d',
      'reflexes-background': '#eed49f',
      'reflexes-font-color': '#3d2e0a',
      'resilience-background': '#f5a97f',
      'resilience-font-color': '#3d2008',
      'willpower-background': '#f5bde6',
      'willpower-font-color': '#3d0e2e',
      'stamina-background': '#a6da95',
      'stamina-font-color': '#15330e',
      'resolve-background': '#91d7e3',
      'resolve-font-color': '#0d3038',
      'wounds-background': '#ed8796',
      'wounds-font-color': '#401219',
      'uncommon-background': '#a6da95',
      'uncommon-font-color': '#15330e',
      'rare-background': '#eed49f',
      'rare-font-color': '#3d2e0a',
      'unique-background': '#f5bde6',
      'unique-font-color': '#3d0e2e',
      'critical-success-background': '#7dc4e4',
      'critical-success-font-color': '#0a2733',
      'success-background': '#a6da95',
      'success-font-color': '#15330e',
      'failure-background': '#eed49f',
      'failure-font-color': '#3d2e0a',
      'critical-failure-background': '#ee99a0',
      'critical-failure-font-color': '#40141a',
      'succeeded-font-color': '#8aadf4',
      'failed-font-color': '#ed8796',
      'lesser-background': '#f0c6c6',
      'lesser-color': '#6e1f29',
      'greater-background': '#b7e0a9',
      'greater-color': '#1d3a12',
      'meter-background': '#181926',
      'custom-effect-primary': '#c6a0f6',
      'custom-effect-secondary': '#eed49f',
      'custom-effect-font-color': '#181926',
      'expired-effect-primary': '#eed49f',
      'expired-effect-secondary': '#ee99a0',
      'expired-effect-font-color': '#181926',
      'initiative-effect-primary': '#ee99a0',
      'initiative-effect-secondary': '#c6a0f6',
      'initiative-effect-font-color': '#181926',
      'permanent-effect-primary': '#8bd5ca',
      'permanent-effect-secondary': '#a6da95',
      'permanent-effect-font-color': '#181926',
      'turn-end-effect-primary': '#f5bde6',
      'turn-end-effect-secondary': '#c6a0f6',
      'turn-end-effect-font-color': '#181926',
      'turn-start-effect-primary': '#c6a0f6',
      'turn-start-effect-secondary': '#8bd5ca',
      'turn-start-effect-font-color': '#181926',
      'chat-public-background': '#2a2d42',
      'chat-public-header-background': '#1e2030',
      'chat-public-badge-background': '#494d64',
      'chat-public-badge-font-color': '#cad3f5',
      'chat-secret-background': '#2d3050',
      'chat-secret-header-background': '#23264a',
      'chat-secret-badge-background': '#3d4178',
      'chat-secret-badge-font-color': '#cdd1fa',
      'chat-gm-background': '#38283f',
      'chat-gm-header-background': '#2c1f33',
      'chat-gm-badge-background': '#553c61',
      'chat-gm-badge-font-color': '#e8d4f2',
      'font-family-normal': "'Lato'",
      'font-family-rich-text': "'Open Sans'",
   }),
});

export default MACCHIATO;
