import '~/styles/Global.scss';
import '~/styles/Lato.scss';
import '~/styles/OpenSans.scss';
import onCombatNextTurn from '~/hooks/OnCombatNextTurn.js';
import onCombatPreviousTurn from '~/hooks/OnCombatPreviousTurn.js';
import onDeleteChatMessage from '~/hooks/OnDeleteChatMessage.js';
import onGetActorDirectoryEntryContext from '~/hooks/OnGetActorDirectoryEntryContext.js';
import onGetChatLogEntryContext from '~/hooks/OnGetChatLogEntryContext.js';
import onGetItemDirectoryEntryContext from '~/hooks/OnGetItemDirectoryEntryContext.js';
import onRenderJournalSheet from '~/hooks/OnRenderJournalSheet.js';
import onRenderJournalTextPageSheet from '~/hooks/OnRenderJournalTextPageSheet.js';
import onceInit from '~/hooks/OnceInit.js';
import onceReady from '~/hooks/OnceReady.js';
import onceSetup from '~/hooks/OnceSetup.js';

Hooks.on('combatNextTurn', onCombatNextTurn);
Hooks.on('combatPreviousTurn', onCombatPreviousTurn);
Hooks.on('deleteChatMessage', onDeleteChatMessage);
Hooks.on('getActorContextOptions', onGetActorDirectoryEntryContext);
Hooks.on('getChatMessageContextOptions', onGetChatLogEntryContext);
Hooks.on('getItemContextOptions', onGetItemDirectoryEntryContext);
Hooks.on('renderJournalEntrySheet', onRenderJournalSheet);
Hooks.on('renderJournalEntryPageProseMirrorSheet', onRenderJournalTextPageSheet);
Hooks.once('init', onceInit);
Hooks.once('ready', onceReady);
Hooks.once('setup', onceSetup);
