import '~/styles/Global.scss';
import '~/styles/Lato.scss';
import '~/styles/Mixins/AttributeMixins.scss';
import '~/styles/Mixins/BorderMixins.scss';
import '~/styles/Mixins/ButtonMixins.scss';
import '~/styles/Mixins/FlexMixins.scss';
import '~/styles/Mixins/FontMixins.scss';
import '~/styles/Mixins/InputMixins.scss';
import '~/styles/Mixins/ListMixins.scss';
import '~/styles/Mixins/LabelMixins.scss';
import '~/styles/Mixins/MarginMixins.scss';
import '~/styles/Mixins/PaddingMixins.scss';
import '~/styles/Mixins/RarityMixins.scss';
import '~/styles/Mixins/ResistanceMixins.scss';
import '~/styles/Mixins/SeparatorMixins.scss';
import '~/styles/Mixins/SystemMixins.scss';
import '~/styles/Mixins/TagMixins.scss';
import '~/styles/OpenSans.scss';
import '~/styles/Variables.scss';
import onCombatNextTurn from '~/hooks/OnCombatNextTurn.js';
import onGetActorDirectoryEntryContext from '~/hooks/OnGetActorDirectoryEntryContext.js';
import onGetChatLogEntryContext from '~/hooks/OnGetChatLogEntryContext.js';
import onGetItemDirectoryEntryContext from '~/hooks/OnGetItemDirectoryEntryContext.js';
import onPreDeleteChatMessage from '~/hooks/OnPreDeleteChatMessage.js';
import onRenderChatMessageHTML from '~/hooks/OnRenderChatMessageHTML.js';
import onRenderJournalSheet from '~/hooks/OnRenderJournalSheet.js';
import onRenderJournalTextPageSheet from '~/hooks/OnRenderJournalTextPageSheet.js';
import onceInit from '~/hooks/OnceInit.js';
import onceReady from '~/hooks/OnceReady.js';
import onceSetup from '~/hooks/OnceSetup.js';

Hooks.on('combatNextTurn', onCombatNextTurn);
Hooks.on('getActorDirectoryEntryContext', onGetActorDirectoryEntryContext);
Hooks.on('getChatLogEntryContext', onGetChatLogEntryContext);
Hooks.on('getItemDirectoryEntryContext', onGetItemDirectoryEntryContext);
Hooks.on('preDeleteChatMessage', onPreDeleteChatMessage);
Hooks.on('renderChatMessageHTML', onRenderChatMessageHTML);
Hooks.on('renderJournalSheet', onRenderJournalSheet);
Hooks.on('renderJournalTextPageSheet', onRenderJournalTextPageSheet);
Hooks.once('init', onceInit);
Hooks.once('ready', onceReady);
Hooks.once('setup', onceSetup);
